### ISSUE TITLE
Incorrect scaling with different aspect ratios

### ISSUE THREAD

**Issue by chr4ss12** [himelbrand/react-native-pixel-perfect#3]
Looks like the logic is not taking into an account devices with different aspect ratios (for example A31 w aspect ratio of 20:9),

I've added the following to calculate aspectRatioMultiplier:

```
    const { height: fullHeight, width: fullWidth } = Dimensions.get('screen');
    const realAspectRatio = fullWidth / fullHeight;
    const designAspectRatio = designSize.width / designSize.height;

    const aspectRatioMultiplier = realAspectRatio / designAspectRatio;
 ```
 
 which then can be used in the sizing calculation:
 
 
 ```
     return size => RESOLUTIONS_PROPORTION * size * aspectRatioMultiplier;
```

and it seems to work, tested on devices with following aspect ratios:

16:9
20:9

and with different pixelratios (2.625, 1, 2)

**Comment by himelbrand** [comment]
Thanks,
This wasn't supported since when I wrote this package other aspect ratio were not very common (curved screen were very new)

You can make a PR and I'll merge it or I'll add this fix over the weekend.

If you do make a PR please add a description of the used logic in the description.

**Comment by chr4ss12** [comment]
I can do a PR, would you mind thinking if the calculation above makes sense? I did test it as said and it looked OK with the few devices I tested, but I can't explain exactly why it works or if it makes sense, to be honest I don't understand the initial logic well to begin with (finding diagonals of the screens using pythagorean and just finding the scale factor based on that).



basically on my 20/9 device with 1080x2400 resolution, everything looked significantly bigger for some reason than on any other 16:9 device (I used const DEFAULT_SCREENSIZE = PREDEF_RES.iphone6.dp; for my default screensize)

My logic was that if I find how many times is the source aspect ratio bigger than the target aspect ratio, and basically scale the units by. In case the aspect ratios match I would be multiplying by 1 thus keeping the existing behaviour, and by pure luck it seemed to work, but don't know why

**Comment by chr4ss12** [comment]
the above logic does not work with other devices (ipads have diff aspect ratios), such as 4:3 (10.5" ipad pro), and 10:7 (11" ipad pro), will investigate

**Comment by himelbrand** [comment]
Thanks for the details,
I'll try to get to it this weekend, busy with work.
Maybe I can come up with some solution

**Comment by chr4ss12** [comment]
hi @himelbrand, apologies, ignore this thread completely, I have completely misunderstood how react-native device independent pixels work as well the purpose of this library.

As of right now, this library as it stands, works perfectly on wide range of devices with different screen aspect ratios and does exactly what it was designed to do.
